name: DEBUG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone仓库
        uses: actions/checkout@v3
        with:
          ref: main

      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖, 执行代码
        run: |
          pip install --upgrade pip
          pip install httpx[http2]
          python3 debug.py
        env: |
          DEBUG: ${{ secrets.DEBUG }}
